# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=2)),
                ('date', models.DateTimeField(verbose_name='match date')),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('fthg', models.IntegerField(default=0)),
                ('ftag', models.IntegerField(default=0)),
                ('ftr', models.CharField(max_length=1)),
            ],
        ),
    ]
