# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20170105_1613'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([('date', 'home_team', 'away_team')]),
        ),
    ]
