# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20170106_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='ftag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fthg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ftr',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
