# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0004_auto_20170106_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ftag',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fthg',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='ftr',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
