# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20170106_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ftr',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
