# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_auto_20170109_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Division'),
            preserve_default=False,
        ),
    ]
