# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='attack_strength',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='defense_strength',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='total_games',
            field=models.IntegerField(default=1),
        ),
    ]
