# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_auto_20170113_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='ftag',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='division',
            name='fthg',
            field=models.IntegerField(default=1),
        ),
    ]
