# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20170113_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_win',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='draw',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_win',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='pftag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='pfthg',
            field=models.IntegerField(default=0),
        ),
    ]
