# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_auto_20170113_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='attack_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='defense_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ftag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='fthg',
            field=models.IntegerField(default=0),
        ),
    ]
