# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_auto_20170113_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='ftagc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='fthgc',
            field=models.IntegerField(default=0),
        ),
    ]
