# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_auto_20170118_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='attack_strength',
            new_name='away_attack_strength',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='defense_strength',
            new_name='away_defense_strength',
        ),
        migrations.AddField(
            model_name='team',
            name='home_attack_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='home_defense_strength',
            field=models.FloatField(default=0),
        ),
    ]
