# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_auto_20170118_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='pftag',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='pfthg',
            field=models.FloatField(default=0),
        ),
    ]
