# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_auto_20170124_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='record',
            field=models.CharField(default='', max_length=5),
        ),
    ]
