# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_match_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='record',
        ),
        migrations.AddField(
            model_name='team',
            name='record',
            field=models.CharField(default='', max_length=5),
        ),
    ]
