# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0034_auto_20170202_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='display_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
