# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0035_division_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
