# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0036_league_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league_entry',
            name='record',
            field=models.CharField(default='', max_length=10),
        ),
    ]
