# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0037_league_entry_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='over',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='under',
            field=models.FloatField(default=0),
        ),
    ]
