# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0039_auto_20170202_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='betfair_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
