# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0040_team_betfair_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='betfair_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
