# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0041_division_betfair_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_0', models.FloatField(default=0)),
                ('goals_1', models.FloatField(default=0)),
                ('goals_2', models.FloatField(default=0)),
                ('goals_3', models.FloatField(default=0)),
                ('goals_4', models.FloatField(default=0)),
                ('goals_5', models.FloatField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='probabilities',
            unique_together=set([('match', 'team')]),
        ),
    ]
