# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0043_auto_20170213_1615'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='probability',
            unique_together=set([('match', 'team', 'name', 'probability_type')]),
        ),
    ]
